'use client';
import { motion } from 'framer-motion';
import { Download, FileText, CheckCircle2, AlertTriangle, X } from 'lucide-react';
import { GlassPanel } from '@/components/ui/GlassPanel';
import { GlowButton } from '@/components/ui/GlowButton';
import { TechnicalLabel } from '@/components/ui/TechnicalLabel';
import { useProductAssemblyStore } from '@/store/productAssemblyStore';

export function ProductAssemblyReport({ onClose }: { onClose: () => void }) {
  const { currentAssembly, parts } = useProductAssemblyStore();

  const installedParts = parts.filter((p) => p.status === 'installed');
  const removedParts = parts.filter((p) => p.status === 'removed');

  const handleDownload = () => {
    const reportData = {
      assemblyName: currentAssembly.name,
      category: currentAssembly.category,
      totalPartsCount: parts.length,
      installedCount: installedParts.length,
      removedCount: removedParts.length,
      bomPartsList: parts.map((p) => ({
        id: p.id,
        name: p.name,
        category: p.category,
        partNumber: p.partNumber,
        status: p.status,
        detectionConfidence: p.detectionConfidence,
        visibility: p.visibility,
        material: p.material,
        dependencies: p.dependencies,
      })),
      generatedAt: new Date().toISOString(),
      disclaimer: 'Generated by AssemblyOS Physical Product Intelligence.',
    };

    const text = JSON.stringify(reportData, null, 2);
    const blob = new Blob([text], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `assembly-report-${currentAssembly.id}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 select-none"
      style={{ background: 'rgba(0,0,0,0.85)', backdropFilter: 'blur(10px)' }}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="w-full max-w-xl"
      >
        <GlassPanel className="p-6 border border-[rgba(255,255,255,0.1)]">
          <div className="flex items-start justify-between pb-4 border-b border-[rgba(255,255,255,0.06)]">
            <div>
              <TechnicalLabel variant="accent">3D ASSEMBLY REPORT</TechnicalLabel>
              <h2 className="text-[18px] font-bold text-[#F5F7FA] mt-1">{currentAssembly.name}</h2>
              <p className="font-mono text-[10px] text-[rgba(245,247,250,0.45)] mt-0.5">
                Mechanical Hierarchy, BOM & Dependency Audit
              </p>
            </div>
            <button onClick={onClose} className="p-1.5 rounded-lg text-[rgba(245,247,250,0.4)] hover:text-[#F5F7FA]">
              <X size={18} />
            </button>
          </div>

          <div className="grid grid-cols-3 gap-2.5 my-4">
            <div className="p-3 rounded-xl bg-[rgba(255,255,255,0.02)] border border-[rgba(255,255,255,0.06)]">
              <span className="font-mono text-[9px] uppercase tracking-wider text-[rgba(245,247,250,0.35)] block">
                Total Parts
              </span>
              <span className="font-mono text-xl font-bold text-[#8BE9FF] mt-0.5 block">{parts.length}</span>
            </div>
            <div className="p-3 rounded-xl bg-[rgba(255,255,255,0.02)] border border-[rgba(255,255,255,0.06)]">
              <span className="font-mono text-[9px] uppercase tracking-wider text-[rgba(245,247,250,0.35)] block">
                Installed
              </span>
              <span className="font-mono text-xl font-bold text-[#7DFFB2] mt-0.5 block">
                {installedParts.length}
              </span>
            </div>
            <div className="p-3 rounded-xl bg-[rgba(255,255,255,0.02)] border border-[rgba(255,255,255,0.06)]">
              <span className="font-mono text-[9px] uppercase tracking-wider text-[rgba(245,247,250,0.35)] block">
                Detached
              </span>
              <span className="font-mono text-xl font-bold text-[#FF7F8A] mt-0.5 block">
                {removedParts.length}
              </span>
            </div>
          </div>

          {removedParts.length > 0 && (
            <div className="mb-4 p-3 rounded-xl bg-[rgba(255,127,138,0.08)] border border-[rgba(255,127,138,0.25)] space-y-1">
              <div className="flex items-center gap-1.5 text-[#FF7F8A] font-mono text-[10px] uppercase font-bold">
                <AlertTriangle size={13} />
                <span>INCOMPLETE ASSEMBLY DETECTED</span>
              </div>
              <p className="text-xs text-[rgba(245,247,250,0.7)]">
                The following parts are detached: {removedParts.map((p) => p.name).join(', ')}.
              </p>
            </div>
          )}

          <div className="mb-5 max-h-36 overflow-y-auto space-y-1 pr-1 font-mono text-[11px]">
            <TechnicalLabel className="block mb-2">BOM SAMPLE</TechnicalLabel>
            {parts.slice(0, 5).map((p) => (
              <div
                key={p.id}
                className="flex items-center justify-between p-2 rounded-lg bg-[rgba(255,255,255,0.02)] border border-[rgba(255,255,255,0.04)]"
              >
                <span className="text-[#F5F7FA]">{p.name}</span>
                <span className="text-[rgba(245,247,250,0.4)]">{p.partNumber}</span>
              </div>
            ))}
          </div>

          <div className="flex gap-3">
            <GlowButton variant="primary" size="md" icon={<Download size={14} />} onClick={handleDownload} className="flex-1">
              Download Report (JSON)
            </GlowButton>
            <GlowButton variant="ghost" size="md" onClick={onClose} className="flex-1">
              Close
            </GlowButton>
          </div>
        </GlassPanel>
      </motion.div>
    </div>
  );
}
